"""Default .eigenhelm.toml template used by `eh init`."""

DEFAULT_CONFIG_TEMPLATE = """\
# eigenhelm project configuration
# Generated by `eh init`. Edit to suit your project.
# Documentation: https://github.com/metacogdev/eigenhelm

# Optional: path to a pre-trained eigenspace model (.npz)
# model = "models/eigenspace.npz"

# Optional: default language override for all files (e.g., "python", "javascript")
# language = "python"

# Global accept/reject thresholds.
# Scores <= accept  -> "accept" decision
# Scores in between -> "warn" decision
# Scores >= reject  -> "reject" decision
[thresholds]
accept = 0.3
reject = 0.7

# Optional: treat all "warn" decisions as "reject" (useful for strict CI pipelines)
# strict = false

# Path-specific threshold overrides (last-match-wins).
# Each [[paths]] block overrides global thresholds for files matching its glob.

# Example: relaxed thresholds for generated or vendored code
# [[paths]]
# glob = "vendor/**"
# [paths.thresholds]
# accept = 0.5
# reject = 0.95

# Example: strict thresholds for core source
# [[paths]]
# glob = "src/core/**"
# [paths.thresholds]
# accept = 0.2
# reject = 0.6

# Optional: map file extensions to language keys.
# Useful for non-standard extensions (e.g., .jsx -> javascript).
# [language_overrides]
# ".jsx" = "javascript"
# ".tsx" = "typescript"
"""
