"""Unit tests for file categorization heuristics (018-usecase-benchmarks, T004)."""

from __future__ import annotations

from pathlib import Path


from eigenhelm.validation.categorize import categorize_file
from eigenhelm.validation.usecase_models import FileCategory


class TestFilenameCategorization:
    """Categorization based on filename patterns."""

    def test_init_file(self) -> None:
        content = 'from .foo import bar\n\n__all__ = ["bar"]\n'
        assert categorize_file("src/pkg/__init__.py", content=content) == FileCategory.INIT

    def test_init_with_logic_is_implementation(self) -> None:
        content = "def setup():\n    configure_logging()\n    return App()\n\nclass App:\n    pass\n"
        assert categorize_file("src/pkg/__init__.py", content=content) == FileCategory.IMPLEMENTATION

    def test_test_file_by_prefix(self) -> None:
        assert categorize_file("test_auth.py") == FileCategory.TEST

    def test_test_file_by_suffix(self) -> None:
        assert categorize_file("auth_test.py") == FileCategory.TEST

    def test_file_under_tests_dir(self) -> None:
        assert categorize_file("tests/conftest.py") == FileCategory.TEST

    def test_file_under_test_dir(self) -> None:
        assert categorize_file("test/helpers.py") == FileCategory.TEST


class TestDirectoryCategorization:
    """Categorization based on directory location."""

    def test_models_dir_with_schema_content(self) -> None:
        content = "from dataclasses import dataclass\n\n@dataclass\nclass User:\n    id: str\n    name: str\n"
        assert categorize_file("src/models/user.py", content=content) == FileCategory.SCHEMA

    def test_schemas_dir(self) -> None:
        content = "class Config:\n    debug: bool = False\n"
        assert categorize_file("src/schemas/config.py", content=content) == FileCategory.SCHEMA

    def test_types_dir(self) -> None:
        content = "type UserId = str\n"
        assert categorize_file("src/types/ids.py", content=content) == FileCategory.SCHEMA


class TestContentCategorization:
    """Categorization based on content analysis."""

    def test_generated_marker(self) -> None:
        content = "# Generated by protoc\n\nclass Msg:\n    pass\n"
        assert categorize_file("src/proto/msg_pb2.py", content=content) == FileCategory.GENERATED

    def test_at_generated_marker(self) -> None:
        content = "# @generated\n\nFOO = 1\n"
        assert categorize_file("src/gen.py", content=content) == FileCategory.GENERATED

    def test_normal_py_file(self) -> None:
        content = "def process(data):\n    return data.strip()\n"
        assert categorize_file("src/utils.py", content=content) == FileCategory.IMPLEMENTATION


class TestConfigFiles:
    """Non-.py config files."""

    def test_toml_is_schema(self) -> None:
        assert categorize_file("pyproject.toml") == FileCategory.SCHEMA

    def test_yaml_is_schema(self) -> None:
        assert categorize_file("config.yaml") == FileCategory.SCHEMA

    def test_json_is_schema(self) -> None:
        assert categorize_file("package.json") == FileCategory.SCHEMA


class TestOverrides:
    """Override mechanism."""

    def test_override_wins(self) -> None:
        overrides = {"src/special.py": FileCategory.GENERATED}
        assert (
            categorize_file("src/special.py", overrides=overrides) == FileCategory.GENERATED
        )

    def test_override_with_path_object(self) -> None:
        overrides = {"src/special.py": FileCategory.TEST}
        assert (
            categorize_file(Path("src/special.py"), overrides=overrides) == FileCategory.TEST
        )
